### ISSUE TITLE
Bug: accessing from LAN

### ISSUE THREAD

**Issue by truefriend-cz** [AndronixApp/AndronixOrigin#15] opened 2020-01-04 07:53 UTC
Bug:
Not accessed from others devices in LAN.

**Comment by imprakharshukla** [comment] 2020-01-05 05:22
Be more specific with the process you followed. It will all work if you're on the same network. I am using it right now. **To let us help you further please specify everything you did in the first place**

**Comment by ultrahacx** [comment] 2020-01-05 06:48
Type ifconfig in a new Termux session and copy your wlan ip address which will be something like 192.168.xx.xx You need to copy that ip and paste that in VNC Viewer on other device present in your LAN with the proper port number which was provided when you started the vncserver

**Comment by truefriend-cz** [comment] 2020-01-05 18:21
After basic install i install:
1. selected Debian
2. apt-get update
3. apt-get upgrade
4. Instal net-tools (for ifconfig) and get IP adress from ifconfig command
5. apt-get install openssh-server
6. Installed webmin from http://www.webmin.com/deb.html
7. Open PuTTy from other device and I'm trying to connect to ssh but ssh server is not available.
8-9. Open web browser from other device and I'm trying connect to webmin server but webmin server is not available.

Ping to device is works but not services.

Other services such as samba server and others have this problem. I haven't tried VNC and I don't need a graphical interface so I skipped the step that installs the desktop environment.

**Comment by Aerox912** [comment] 2020-01-06 13:34
You don't have access to systemd services at all, which is by design. 
Every service you need to manually start on the shell and background with something like nohup. 

This is NOT a Linux like your PC where you can do systemctl start service etc.

Go to discord for help, I'm closing this ticket since it has nothing to do with our distro, it's the way you use it.

**Closed by Aerox912** 2020-01-06 13:34 UTC

**Comment by truefriend-cz** [comment] 2020-01-06 23:49
After get info show after run sh from Termux show system as "Debian Buster". It is Linux.

I will not use other resources. If you know the answer then give it to me and other users here. You publish a product for which you want money. If you do not want to pay attention, I request a refund. GitHub is listed as one of the contact points, so I use it. If I have an answer or a solution to get yourself, pay me for it.

**Comment by ultrahacx** [comment] 2020-01-07 03:51
First of all I would like to let you know that you dont know how to report errors and ask for support which was the reason you were asked to clear out yourself on the first place. Whatever you have reported as your first point is still unclear to me. 

Secondly i would request you to use some of your basic sense and think about the limitations which you are dealing with. You raised an issue labelled as bug without any proper description. When someone is informing you that the process you follow has certain restrictions and you can contact us on Discord for more help and information. You need to clear out with your common sense that what is meant by "FULL LINUX SYSTEM".

At last if you just want a refund send us the screenshot of the Google purchase receipt on our Discord support channel or you can also mail it to us cause you dont seem to be co-operative with us.
